### ISSUE TITLE
Allow text string with multiple line to be encoded

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [isman7/gimp-qrcode#2]
With this support it’s possible to include some specific contents as ZXing Project listed.
https://github.com/zxing/zxing/wiki/Barcode-Contents

**Comment by isman7** [comment]
Hey! I'm not currently maintaning this repository, some day when GIMP 3 is fully released, it might be rewritten to Python 3. I think you are asking for more complex encoding for QR Codes, this is entirely done here using a 3rd party library in Python, you might want to ask for the support there: https://github.com/lincolnloop/python-qrcode
